// Lesson 12 - Coupled chemistry and coulometry.
//
// Source syllabus: Bagotsky ch.17-18 and Bard & Faulkner ch.11-12. The
// chapters set the coverage and the numbers; every sentence, formula and
// question here is original.

import type { Lesson } from "./types";
import { lesson12Mcq } from "./lesson-12.mcq";

export const lesson12: Lesson = {
  slug: "lesson-12",
  label: "Lesson 12",
  title: "Coupled chemistry and coulometry",
  summary:
    "Real electrode reactions are rarely alone. The product of a " +
    "faradaic step often reacts again in solution before it can migrate " +
    "away, or the reactant is regenerated by an upstream reaction. These " +
    "coupled homogeneous reactions distort every trace we have met - " +
    "the voltammogram, the chronoamperometric current, the impedance " +
    "spectrum - and learning to read those distortions is how mechanisms " +
    "are solved. The lesson then scales the same chemistry up: bulk " +
    "electrolysis, coulometry as analysis, and the engineering shape of " +
    "a reactor.",
  order: 12,
  minutes: 55,
  mcq: lesson12Mcq,
  intro: [
    {
      kind: "para",
      text:
        "Until now we have assumed one reaction at the electrode: O + ne " +
        "reversibly gives R. That is the exception, not the rule. In a " +
        "real cell the product R usually lives in a reactive solution, " +
        "and the analyte O is often produced or consumed by reactions " +
        "that never touch the electrode. The electrode's job is then " +
        "less a single step and more the first move of a sequence.",
    },
    {
      kind: "para",
      text:
        "Following Bagotsky ch.17-18 and Bard & Faulkner ch.11-12 we " +
        "first classify those sequences - EC, CE, ECE, catalytic - and " +
        "show exactly how each one bends a voltammogram. Then we scale " +
        "the same chemistry up: bulk electrolysis to completion, " +
        "coulometry as an absolute analytical method, and the reactor " +
        "design questions that decide what a process is allowed to " +
        "cost.",
    },
    {
      kind: "callout",
      variant: "key",
      title: "The one-sentence summary of this lesson",
      body:
        "Homogeneous chemistry coupled to a faradaic step leaves a " +
        "fingerprint on every voltammetric trace; reading that " +
        "fingerprint is mechanistic analysis, and running the sequence " +
        "to exhaustion is coulometric analysis - the two sides of one " +
        "coin.",
    },
  ],
  sections: [
    {
      id: "when-not-alone",
      tone: "azure",
      title: "When the electrode is not alone",
      minutes: 6,
      summary:
        "Most real reactions are sequences: an electron-transfer step " +
        "followed, preceded, or accompanied by homogeneous chemistry. " +
        "Those couplings hide in the shape of the current-time curve.",
      keyPoints: [
        "An EC reaction is an electron transfer followed by a homogeneous reaction that consumes the product.",
        "A CE reaction is a homogeneous reaction that makes the electroactive species, which the electrode then consumes.",
        "An ECE reaction alternates electron transfers and chemical steps.",
        "A catalytic scheme regenerates the reactant at the electrode, so the current is carried by a fast-cycling mediator.",
      ],
      blocks: [
        {
          kind: "para",
          text:
            "Picture the electrode as only one actor in the story. The " +
            "electron-transfer step is the scene it owns; everything " +
            "else happens in the solution around it. A product made at " +
            "the surface may decompose, dimerise, or react with the " +
            "solvent. A reactant may have to be produced by a prior " +
            "hydrolysis or dissociation. The electrode only reports " +
            "what it sees, but what it sees has been filtered by the " +
            "chemistry around it.",
        },
        {
          kind: "para",
          text:
            "The shorthand for those filters is a string of letters. E " +
            "is an electron-transfer step at the electrode; C is a " +
            "homogeneous chemical step in solution. Read them in order " +
            "and you have the mechanism. The four you will meet most " +
            "often are:",
        },
        {
          kind: "list",
          ordered: false,
          items: [
            "**EC** - an electron transfer, then a homogeneous reaction that consumes the product. The return wave shrinks.",
            "**CE** - a homogeneous reaction makes the electroactive species first, then the electrode takes it. The forward wave can be fed by the chemical step.",
            "**ECE** - electron transfer, chemical step, then a second electron transfer at the electrode.",
            "**Catalytic** - the reactant is regenerated by a chemical step, so one molecule of mediator turns over many times of current.",
          ],
        },
        {
          kind: "para",
          text:
            "The diagnostic question is always the same: if I slow down " +
            "and squint at the experiment, what does the coupled step " +
            "do to the trace? Does the reverse peak still come back? " +
            "Does the forward peak grow differently with scan rate? Is " +
            "the limiting current bigger than one electron's worth? The " +
            "next two sections work those answers through.",
        },
      ],
    },
    {
      id: "ec-mechanism",
      tone: "indigo",
      title: "The EC fingerprint on a voltammogram",
      minutes: 8,
      summary:
        "A following chemical reaction eats the product of the " +
        "electron-transfer step. Its effect depends on the competition " +
        "between the chemical clock and the experimental timescale.",
      keyPoints: [
        "If the follow-up reaction is much slower than the scan, the voltammogram looks reversible.",
        "If it is much faster, the product never returns: the reverse peak vanishes and the wave looks irreversible.",
        "In the middle the reverse peak is partially eaten, and its size measures the rate of the coupled reaction.",
        "The ratio of reverse to forward charge tracks the fraction of product that survived to the return scan.",
      ],
      blocks: [
        {
          kind: "para",
          text:
            "Take the simplest coupling: O + e ⇌ R at the electrode, " +
            "then R → P in solution at rate k. Whether the voltammogram " +
            "notices depends on how the chemical clock compares with " +
            "the time you give it. The natural yardstick is the scan " +
            "rate: a faster scan gives the chemistry less time to act " +
            "before you reverse the potential.",
        },
        {
          kind: "para",
          text:
            "Three regimes follow. If k is small, R survives the whole " +
            "experiment and the return wave is intact: the system looks " +
            "cleanly reversible. If k is large, R is gone before you " +
            "reverse, so there is no return wave at all and the couple " +
            "looks irreversible even though the electron transfer " +
            "itself was fast. In between, the reverse wave comes back " +
            "reduced in proportion to how much R survived - and that " +
            "fraction is a direct measure of k.",
        },
        {
          kind: "formula",
          tex: String.raw`\lambda = \frac{k}{a}, \qquad a = \frac{n F v}{R T}`,
          caption:
            "The dimensionless competition between chemistry and the " +
            "scan. When λ is small the chemistry is frozen and the " +
            "wave is reversible; when λ is large the product is " +
            "instantly consumed; the transition region is where you " +
            "measure k.",
        },
        {
          kind: "para",
          text:
            "This is why scan-rate studies are the standard workhorse " +
            "of mechanism. Run the same CV at 0.02, 0.2, and 2 V/s and " +
            "watch the reverse peak grow back as the scan outruns the " +
            "chemistry. Fitting that growth against λ gives k - the " +
            "rate of a reaction that never touched an electrode, read " +
            "off a voltammogram.",
        },
        {
          kind: "callout",
          variant: "key",
          title: "The voltammogram is a stopwatch",
          body:
            "Changing the scan rate changes how long the electrode " +
            "waits for the return trip. A coupled reaction's rate can " +
            "be extracted by seeing which scan rate halves the reverse " +
            "peak.",
        },
      ],
    },
    {
      id: "catalytic-and-ce",
      tone: "violet",
      title: "Catalytic currents and CE feeding",
      minutes: 8,
      summary:
        "In a CE scheme the electrode is fed by a chemical step; in a " +
        "catalytic scheme its reactant is regenerated in solution. Both " +
        "inflate or reshape the limiting current in ways a simple " +
        "reversible wave never shows.",
      keyPoints: [
        "In a CE mechanism the electroactive species is made by a preceding chemical step; the electrode's limiting current decays once that step is starved.",
        "In a catalytic (EC') mechanism the reactant is regenerated by a chemical partner, so the current is larger than a one-electron wave from that analyte alone.",
        "A catalytic current grows with the concentration of the chemical regenerating the mediator, not with the mediator itself.",
        "Both mechanisms look like ordinary chemistry on the trace; both become diagnostic only when scan rate or concentration is varied.",
      ],
      blocks: [
        {
          kind: "para",
          text:
            "A CE mechanism is the mirror of EC. First a homogeneous " +
            "step makes the species O, then O diffuses to the electrode " +
            "and is reduced. If the chemical step is slow, it cannot " +
            "keep up with the electrode's appetite, and the limiting " +
            "current is capped by how fast O is made rather than by " +
            "how fast O diffuses. The tell is in the scan-rate " +
            "dependence: instead of the Randles-Sevcik sqrt(v) rise, " +
            "the peak flattens, because feeding, not transport, is " +
            "the bottleneck.",
        },
        {
          kind: "para",
          text:
            "EC' is the one that matters most in energy. Add a " +
            "chemical partner that hands an electron back to the " +
            "reduced form, regenerating O. Now one O molecule can be " +
            "reduced many times: the electrode sees a catalytic " +
            "current, a plateau that no reversible couple would " +
            "produce at that concentration of O. The current scales " +
            "with the concentration of the *chemical partner*, not of " +
            "O - which is the diagnostic signature of the scheme.",
        },
        {
          kind: "formula",
          tex: String.raw`\text{EC': } O + e^- \rightleftharpoons R, \qquad R + Z \xrightarrow{k} O + P, \qquad i \propto \sqrt{k[Z]}`,
          caption:
            "Catalytic EC' scheme. The reduced form R is returned to O " +
            "by the chemical partner Z, so the electrode turns over the " +
            "same O again and again. The steady current scales with the " +
            "square root of k[Z].",
        },
        {
          kind: "para",
          text:
            "That square-root dependence is the working tool. Vary " +
            "[Z] and watch the plateau grow as sqrt([Z]); that is " +
            "k at work. Vary the scan rate and the plateau survives " +
            "much better than a diffusion peak would, because the " +
            "recycling of O replenishes the surface supply. Electro-" +
            "catalysis - an enzyme replenished by a cofactor, a metal " +
            "centre regenerated by H2 - is this scheme drawn in " +
            "biological or materials colours.",
        },
      ],
    },
    {
      id: "bulk-electrolysis",
      tone: "rose",
      title: "Bulk electrolysis: finishing the job",
      minutes: 7,
      summary:
        "Voltammetry samples a percent of the analyte. Bulk electrolysis " +
        "pushes the reaction to completion - the basis of gravimetry, " +
        "of refining, and of the coulometric analysis that follows.",
      keyPoints: [
        "Bulk electrolysis holds the electrode at a potential where the target reaction is the only one running, and lets it proceed to exhaustion.",
        "The current starts high and decays as the analyte is consumed; the total charge passed is the analyte's stoichiometry.",
        "Exhaustive electrolysis demands high current efficiency: side reactions would bleed off the charge budget.",
        "Porous flow-through or stirred cells are used because diffusion alone cannot keep a large bath fed.",
      ],
      blocks: [
        {
          kind: "para",
          text:
            "A voltammogram touches a few percent of the solution " +
            "nearest the electrode and reports on the rest indirectly. " +
            "Bulk electrolysis does the opposite: it keeps going until " +
            "there is nothing left to convert. Set the potential deep " +
            "in the mass-transfer-limited region, close the circuit, and " +
            "the current does the counting as the analyte is depleted.",
        },
        {
          kind: "para",
          text:
            "The current-time trace looks like the chronoamperometric " +
            "decay of Lesson 8, but with one crucial difference: here " +
            "the reactor is stirred or flowed through, so the depletion " +
            "is of the *whole* solution, and the current decays roughly " +
            "exponentially as the bulk concentration falls. The " +
            "experiment is finished when the current returns to the " +
            "background - the charge passed on the way is `zFn` of the " +
            "analyte that was there.",
        },
        {
          kind: "callout",
          variant: "warn",
          title: "Exhaustive means selective",
          body:
            "To exhaust one species without triggering another, the " +
            "potential window must be chosen between their formal " +
            "potentials. A wide-apart couple pair can be separated " +
            "into two sequential electrolyses; overlapping couples " +
            "cannot be cleanly separated at all.",
        },
        {
          kind: "para",
          text:
            "Two practical constraints follow. The electrode must be " +
            "big enough, the stirring strong enough, that the " +
            "whole-bath supply can keep up - hence large cathodes " +
            "of copper gauze, mercury pools, or porous flow beds. And " +
            "the current efficiency must really be 100 %: solvent " +
            "breakdown or an oxygen leak would pass charge without " +
            "touching the analyte.",
        },
      ],
    },
    {
      id: "coulometry-as-analysis",
      tone: "coral",
      title: "Coulometry: charge as the standard",
      minutes: 7,
      summary:
        "In bulk electrolysis the integrated current is the amount of " +
        "analyte. Elevated to an analytical principle, that is " +
        "coulometry - an absolute method that needs no chemical " +
        "standard, only the Faraday constant.",
      keyPoints: [
        "Controlled-potential coulometry integrates the decaying current until the analyte is exhausted; Q = zFn.",
        "Controlled-current coulometry feeds a steady current and times the endpoint - a titration without a burette.",
        "Both are absolute because the Faraday constant is the calibrant; the only assumptions are unit current efficiency and a true endpoint.",
        "Practical electrolytes, reference electrodes, and endpoint detectors differ between the two variants.",
      ],
      blocks: [
        {
          kind: "para",
          text:
            "Bulk electrolysis finishes a reaction; coulometry counts " +
            "what it did. In controlled-potential coulometry the " +
            "potential is held where only the target reaction runs, and " +
            "the current - high at first, decaying as the analyte is " +
            "consumed - is integrated until it reaches baseline. The " +
            "area under that decay curve is the total charge, and " +
            "Q = zFn converts charge into moles. No titrant, no " +
            "standard solution: the electron is the reagent and F is " +
            "its stoichiometry.",
        },
        {
          kind: "formula",
          tex: String.raw`n = \frac{1}{zF}\int_0^{\infty} i(t)\, dt`,
          caption:
            "Controlled-potential coulometry. Integrate the current " +
            "until the analyte is spent; the integrated charge, divided " +
            "by zF, is the amount originally present.",
        },
        {
          kind: "para",
          text:
            "Controlled-current coulometry swaps the roles: fix the " +
            "current and time how long it runs until an endpoint sensor " +
            "signals that the reaction is complete. This is a titration " +
            "with electrons as the titrant and the electrode as the " +
            "reagent reservoir - a coulometric titration. Its accuracy " +
            "comes from the steadiness of the current and the sharpness " +
            "of the endpoint, both of which are instruments problems, " +
            "not chemistry problems.",
        },
        {
          kind: "para",
          text:
            "Both variants stand on the same two pillars: 100 % current " +
            "efficiency and a detectable endpoint. Everything else - " +
            "the integrator, the reference electrode, the endpoint " +
            "electrode - is there to protect one of those two. When " +
            "they hold, the result is as absolute as the Faraday " +
            "constant, which is why coulometry defined several of the " +
            "fundamental units of chemistry.",
        },
      ],
    },
    {
      id: "reactor-design",
      tone: "amber",
      title: "Designing the real cell",
      minutes: 7,
      summary:
        "Scale the chemistry up and the problem changes shape. A " +
        "practical electrochemical reactor is a negotiation among " +
        "current, voltage, heat, separators, and electrode area.",
      keyPoints: [
        "A practical cell is a stack: anode, separator, cathode, and a way to bring reactants to each surface.",
        "Throughput scales with electrode area per unit volume; porous and three-dimensional electrodes maximise it.",
        "The cell voltage must cover the thermodynamic requirement plus all overpotentials and ohmic drops; every millivolt saved is money.",
        "Separators and membranes keep products apart, so the reactor is also a chemical engineering device.",
      ],
      blocks: [
        {
          kind: "para",
          text:
            "A laboratory beaker is a reactor, but not a practical one. " +
            "Industrial electrochemistry is the same electrode " +
            "reactions in a heat exchanger, a separator, a gas " +
            "collector, and an electrical busbar. The design question " +
            "is never which reaction to run - that is chemistry - but " +
            "how much current, how much voltage, how much area, and " +
            "what goes where.",
        },
        {
          kind: "para",
          text:
            "The voltage budget is the central ledger. The thermodynamic " +
            "minimum is the cell EMF, but under load the applied " +
            "voltage must also pay for activation overpotentials at " +
            "both electrodes, the ohmic drop across electrolyte and " +
            "separator, and concentration overpotentials. Every " +
            "millivolt beyond the thermodynamic minimum is heat, and " +
            "heat is money: a 100 mV saving across a large plant is the " +
            "difference between a viable process and a stranded one.",
        },
        {
          kind: "formula",
          tex: String.raw`V_{\text{cell}} = E_{\text{thermo}} + \eta_a + |\eta_c| + i R_{\Omega}`,
          caption:
            "The voltage budget of a real cell. `E_thermo` is the " +
            "reversible requirement; overpotentials and the ohmic drop " +
            "are the taxes. A good reactor minimises all three terms " +
            "while still pushing the current density the plant " +
            "requires.",
        },
        {
          kind: "para",
          text:
            "The area budget matters just as much. Current density is " +
            "current per unit area, so doubling the area at the same " +
            "rate halves the current density and therefore the " +
            "overpotentials. Porous electrodes, rolled or stacked " +
            "configurations, and three-dimensional beds exist to pack " +
            "the largest possible electroactive area into the smallest " +
            "possible volume - the same trick the microelectrode and " +
            "the channel cell of Lesson 10 played at laboratory scale.",
        },
        {
          kind: "callout",
          variant: "term",
          title: "Separator: the silent half of the cell",
          body:
            "Between anode and cathode sits a membrane or separator " +
            "that must pass ions but block products. It is the " +
            "ingredient most people forget, and the one failure of a " +
            "fuel cell, a chlor-alkali plant, or a battery most " +
            "often traces to.",
        },
        {
          kind: "worked",
          title: "Reading an EC rate from the return wave",
          given:
            "An EC couple gives Q_rev/Q_fwd = 0.72 when the switch-back is delayed by 2.0 s. Estimate the first-order rate k of the coupled reaction.",
          steps: [
            String.raw`\text{Survival fraction } = Q_{rev}/Q_{fwd} = e^{-k\tau}`,
            String.raw`0.72 = e^{-2k} \;\Rightarrow\; k = -\ln(0.72)/2`,
            String.raw`k = 0.329/2 \approx 0.164\ \mathrm{s^{-1}}`,
          ],
          result:
            "k is about 0.16 s^-1. The return wave shrank by 28 %, so that is the fraction of product eaten by the homogeneous step during the 2 s wait.",
        },
        {
          kind: "worked",
          title: "Coulometric amount of analyte",
          given:
            "A bulk electrolysis at unit current efficiency finishes with Q = 482 C past a 2-electron reduction. How many moles of analyte were present?",
          steps: [
            String.raw`Q = z F n \;\Rightarrow\; n = Q/(zF)`,
            String.raw`n = 482/(2 \times 96485) = 2.50\times10^{-3}\ \mathrm{mol}`,
          ],
          result:
            "2.5 mmol of analyte. Coulometry turns a current-time integral into a mole count with no standard solution involved.",
        },
      ],
      cta: {
        title: "See what corrodes",
        body:
          "Cells we design on purpose. Next lesson, cells we wish we " +
          "had not built - the chemistry of corrosion, and what a " +
          "civilisation spends defending against it.",
        href: "/lessons/lesson-12/quiz",
        linkLabel: "Take the Lesson 12 quiz",
        secondaryHref: "/lessons/lesson-13",
        secondaryLabel: "Go to Lesson 13",
      },
    },
  ],
};
